# HYSA rates sync

Scrapes current HYSA APY rates and updates `data/hysa_rates/rates.csv`.
Safe to re-run: existing rows are preserved and new observations are appended.

In [1]:
from trades.config import AppConfig
from trades.market_data import hysa_rates as hysa_module

config = AppConfig()

In [2]:
history = hysa_module.update_hysa_rates_cache(config)
print(f"{len(history)} observations cached across {history['bank_id'].n_unique()} banks")

429 observations cached across 10 banks

In [3]:
# Available banks
hysa_module.list_banks(history)

shape: (10, 2)
┌─────────────────────────┬─────────────────────────┐
│ bank_id                 ┆ bank_name               │
│ ---                     ┆ ---                     │
│ str                     ┆ str                     │
╞═════════════════════════╪═════════════════════════╡
│ ally-bank               ┆ Ally Bank               │
│ american-express        ┆ American Express        │
│ cit-bank                ┆ CIT Bank                │
│ capital-one-360         ┆ Capital One 360         │
│ marcus-by-goldman-sachs ┆ Marcus by Goldman Sachs │
│ primis-bank             ┆ Primis Bank             │
│ sallie-mae              ┆ Sallie Mae              │
│ sofi                    ┆ SoFi                    │
│ wealthfront             ┆ Wealthfront             │
│ western-alliance        ┆ Western Alliance        │
└─────────────────────────┴─────────────────────────┘

In [4]:
# Full rate history
history

shape: (429, 4)
┌─────────────────┬─────────────────┬────────────┬─────────┐
│ bank_id         ┆ bank_name       ┆ rate_date  ┆ apy_pct │
│ ---             ┆ ---             ┆ ---        ┆ ---     │
│ str             ┆ str             ┆ date       ┆ f64     │
╞═════════════════╪═════════════════╪════════════╪═════════╡
│ primis-bank     ┆ Primis Bank     ┆ 2022-11-03 ┆ 3.05    │
│ primis-bank     ┆ Primis Bank     ┆ 2022-11-08 ┆ 3.5     │
│ primis-bank     ┆ Primis Bank     ┆ 2022-12-28 ┆ 4.05    │
│ primis-bank     ┆ Primis Bank     ┆ 2023-01-31 ┆ 5.03    │
│ primis-bank     ┆ Primis Bank     ┆ 2023-02-17 ┆ 4.35    │
│ …               ┆ …               ┆ …          ┆ …       │
│ capital-one-360 ┆ Capital One 360 ┆ 2025-10-01 ┆ 3.4     │
│ capital-one-360 ┆ Capital One 360 ┆ 2026-01-08 ┆ 3.3     │
│ capital-one-360 ┆ Capital One 360 ┆ 2026-03-12 ┆ 3.2     │
│ capital-one-360 ┆ Capital One 360 ┆ 2026-04-24 ┆ 3.1     │
│ capital-one-360 ┆ Capital One 360 ┆ 2026-06-02 ┆ 3.0     │
└─────────────────┴─────────────────┴────────────┴─────────┘